on:
    release:
        types: 
            - published
    push:
        
jobs:
    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v4
            - run: ls
