on:
    release:
        types: 
            - published

jobs:
    publish:
        if: github.event.release.draft == false && github.event.release.prerelease == false
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v4

            - run: echo "${{ github.event.release.body }}" >> release.md

            - run: dotnet publish /t:PublishContainer /p:Configuration=Release /p:BuildNumber=${{ github.run_number }}

            - run: docker login -u slepuhin -p ${{ secrets.DOCKERHUB_TOKEN }}

            - run: docker push -a slepuhin/burger

            - run: |
                echo "${{ secrets.KAPIBARA_SSH_PRIVATE_KEY }}" > kapibara
                chmod 600 kapibara
                eval "$(ssh-agent -s)"
                echo "${{ secrets.KAPIBARA_SSH_PASSPHRASE }}" | ssh-add kapibara 
                ssh root@kapibara.mooo.com -i kapibara -o StrictHostKeyChecking=no 'cd /opt/burger && docker compose pull && docker compose up -d'
